server {
    listen 80;

   # API (FastAPI)
    location /api/ {
        proxy_pass http://databridge-server:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Frontend (Next.js)
    location / {
        proxy_pass http://databridge-frontend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}